* 'Line 1: Remove the using directive for 'Microsoft.OpenApi.Models' as the error CS0234 indicates that 'Models' does not exist in 'Microsoft.OpenApi' in the current framework version. Line 11: Remove the duplicate using directive for 'Microsoft.OpenApi.Models' as the error CS0234 indicates that 'Models' does not exist in 'Microsoft.OpenApi' in the current framework version.' in file 'src\eShop.ServiceDefaults\OpenApiOptionsExtensions.cs'